<?php

/**
 * @file
 * Provides a seminar work entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function seminar_work_theme() {
  return [
    'seminar_work' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for seminar work templates.
 *
 * Default template: seminar-work.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the seminar work information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_seminar_work(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
